In [1]:
import pandas as pd

In [2]:
df_trained_generations = pd.read_json("/home/kalashkala/semantic_uncertainty/semantic_uncertainty/root/uncertainty/local_run/train_generations.jsonl", lines=True)
df_trained_generations

,qw_14911--133/133_1320452.txt#0_1,dpql_654--22/22_568872.txt#0_0,wh_261--178/178_730971.txt#0_0,bb_2583--116/116_890131.txt#0_1,qw_7042--85/85_1169294.txt#0_0,sfq_21879--98/98_1195596.txt#0_1,sfq_23311--88/88_314805.txt#0_0,sfq_17180--69/69_1853787.txt#0_1,qb_8254--121/121_426652.txt#0_0,sfq_16063--194/194_3033781.txt#0_0,...,sfq_11200--59/59_543281.txt#0_2,qg_3215--49/49_3215730.txt#0_0,odql_9981--91/91_2263548.txt#0_1,dpql_574--18/18_2642848.txt#0_0,qf_1530--148/148_2476191.txt#0_0,sfq_17363--103/103_1658047.txt#0_0,qb_495--105/105_278738.txt#0_2,odql_14154--68/68_153369.txt#0_1,bb_1774--101/101_942647.txt#0_1,odql_13425--63/63_2328153.txt#0_0
0,{'question': 'The cocktail called a Tom Collin...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,{'question': 'The characters Denisov and Dolok...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,{'question': 'What was the name of Lady Chatte...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,{'question': 'Near Field Communication technol...,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,"{'question': '""In the nursery rhyme beginning ...",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,{'question': 'Which element has the chemical s...,NaN,NaN,NaN,NaN
146,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,{'question': 'What was the name of the Cunard ...,NaN,NaN,NaN
147,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,{'question': 'What is the name given to the ve...,NaN,NaN
148,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,{'question': 'Sesame seeds are a very good die...,NaN
149,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,{'question': 'In which US state is Denali Nati...

In [2]:
model = 'qwen'
df_math_llama = pd.read_csv(f"/home/kalashkala/Datasets/Semantic-Uncertainty/answerable_math/uncertainty_run_{model}_answerable_math_combined.csv")
df_math_llama["LLM_verdict"] = df_math_llama['accuracy'].astype(bool)
df_math_llama.to_csv(f"/home/kalashkala/Datasets/Semantic-Uncertainty/answerable_math/uncertainty_run_{model}_answerable_math_combined_llm_verdict.csv")

In [3]:
aggregate_df = pd.read_csv("/home/kalashkala/continuous-uncertainty/continuous-uncertainty/outputs/llava_internal_diag_v1_question_mean_new/aggregate_metrics.csv")
aggregate_df

,run_name,model_name,sequence_id,category,num_frames,max_ambiguity_index,accuracy,answer_flip_rate,mean_vision_adjacent_jump,max_vision_adjacent_jump,...,yes_no_margin_center_distance_spearman,binary_entropy_center_distance_spearman,mean_attention_entropy_content_tokens,mean_attention_jump_content_tokens,mean_center_distance_spearman_content_tokens,mean_temporal_variance_content_tokens,mean_center_vs_clear_diff_content_tokens,mean_head_entropy_spread_content_tokens,mean_head_image_mass_spread_content_tokens,mean_top_head_vs_mean_divergence_content_tokens
0,llava_internal_diag_v1_question_mean_new,llava-hf/llava-1.5-7b-hf,NExTVideo_0089_3066966990,Compositional,10,7,0.6,0.111111,0.004221,0.005805,...,0.451228,0.451228,5.125707,0.851488,0.423179,5.610084e-07,0.020162,0.662539,0.159986,3.112960
1,llava_internal_diag_v1_question_mean_new,llava-hf/llava-1.5-7b-hf,NExTVideo_0089_6868234420,Semantic,10,4,0.0,0.000000,0.002320,0.003168,...,0.595137,0.650356,5.218066,0.754827,0.625814,3.625897e-07,0.014799,0.644778,0.146082,3.455595
2,llava_internal_diag_v1_question_mean_new,llava-hf/llava-1.5-7b-hf,NExTVideo_0090_5329653093,Semantic,10,5,0.4,0.555556,0.005118,0.007346,...,0.478564,0.496970,5.275913,0.674022,0.273640,2.375035e-07,0.015911,0.625062,0.123599,2.061720
3,llava_internal_diag_v1_question_mean_new,llava-hf/llava-1.5-7b-hf,NExTVideo_0090_7001183247,Compositional,10,3,1.0,0.000000,0.011808,0.018187,...,0.470968,0.366988,5.414609,0.827876,-0.017126,3.921953e-07,0.017376,0.699791,0.173726,3.032526
4,llava_internal_diag_v1_question_mean_new,llava-hf/llava-1.5-7b-hf,NExTVideo_1009_4738042036,Semantic,10,5,0.5,0.111111,0.004815,0.006923,...,0.730116,0.730116,5.205487,0.781415,0.600045,3.878194e-07,0.017341,0.625036,0.136642,3.176750
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87,llava_internal_diag_v1_question_mean_new,llava-hf/llava-1.5-7b-hf,NExTVideo_0031_5516830700,Semantic,10,4,0.7,0.111111,0.006030,0.008206,...,0.006135,-0.018406,5.189232,0.801294,0.520285,4.231352e-07,0.018777,0.646849,0.133775,2.290305
88,llava_internal_diag_v1_question_mean_new,llava-hf/llava-1.5-7b-hf,NExTVideo_0033_2834146886,Geometric,10,4,0.1,0.222222,0.012783,0.018423,...,0.411074,0.533783,5.071520,0.892836,0.368126,5.820485e-07,0.024142,0.691615,0.137568,2.394661
89,llava_internal_diag_v1_question_mean_new,llava-hf/llava-1.5-7b-hf,NExTVideo_0033_3105754589,Semantic,10,4,0.0,0.000000,0.015871,0.027626,...,-0.128844,-0.128844,5.086749,0.845312,0.624587,4.633210e-07,0.017999,0.689483,0.133073,2.467384
90,llava_internal_diag_v1_question_mean_new,llava-hf/llava-1.5-7b-hf,NExTVideo_0034_5296671076,Semantic,10,4,0.3,0.111111,0.009107,0.022627,...,0.816012,0.816012,5.130556,0.798304,0.717845,5.131259e-07,0.020049,0.641528,0.145643,2.841822
91,llava_internal_diag_v1_question_mean_new,llava-hf/llava-1.5-7b-hf,NExTVideo_0039_5351925965,Semantic,10,4,0.1,0.222222,0.006124,0.016533,...,-0.116573,-0.116573,5.333329,0.730728,0.612316,3.024707e-07,0.016240,0.595886,0.128511,3.683053

In [17]:
df = pd.read_csv("/home/kalashkala/recovery-gaps-experiment/data/sampled_1400_uncertainty_run_llama_sciq_combined_llm_verdict_concentration_output_with_distractors.csv")
df

,id,question,ground_truth,low_t_generation,accuracy,n_generations,cluster_assignment_entropy,p_true,LLM_verdict,C_metric,category,candidate_list
0,train::9014,The term “vapor” refers to the gas phase when ...,['boiling temperature'],its critical temperature,0.0,"['the critical point', 'its critical temperatu...",0.90,-0.974489,False,0.127273,incorrect_low,"[""its critical temperature"", ""melting point"", ..."
1,train::3183,What class are centipedes and millipedes in?,['myriapoda'],arthropods,0.0,"['arthropod', 'arthropods', 'arthropod', 'arth...",-0.00,-0.826869,False,0.490909,incorrect_low,"[""arthropods"", ""insecta"", ""crustacea""]"
2,train::10560,What do you call a compound that contains both...,['amino acid'],amino acid,1.0,"['amino acid', 'amino acids', 'amino acid', 'a...",0.50,-0.062665,True,0.345455,correct_low,"[""peptide"", ""ester"", ""ketone""]"
3,train::568,Gas particles can move randomly in what direct...,['all directions'],three,0.0,"['three', 'any direction', 'three-dimensional ...",1.28,-0.829997,False,0.036364,incorrect_low,"[""three"", ""two directions"", ""one direction""]"
4,validation::760,What helps by releasing chemicals that control...,['helper t cells'],helper T cells,1.0,"['lymphocytes', 'helper t cells', 'Th lymphocy...",1.83,-0.127760,True,0.054545,correct_low,"[""macrophages"", ""b cells"", ""neutrophils""]"
...,...,...,...,...,...,...,...,...,...,...,...,...
1395,train::11097,"Water follows where sodium ions lead, due to w...",['osmosis'],osmosis,1.0,"['osmosis', 'osmosis', 'osmosis', 'osmosis', '...",0.33,-0.180150,True,0.818182,correct_high,"[""diffusion"", ""transpiration"", ""capillary acti..."
1396,train::3463,What form does formaldehyde take at room tempe...,['gas'],liquid,0.0,"['a gas', 'liquid', 'gas', 'liquid', 'liquid',...",0.61,-1.600880,False,0.527273,incorrect_high,"[""liquid"", ""crystal"", ""powder""]"
1397,train::8773,Carbon dioxide is an example of a material tha...,['sublimation'],sublimation,1.0,"['sublimation', 'sublimation', 'sublimation', ...",0.33,-0.693766,False,0.818182,incorrect_high,"[""distillation"", ""ionization"", ""crystallization""]"
1398,train::10906,What is the percentage of production transferr...,['trophic efficiency'],10% (or 10 percent),0.0,"['10%', '10%', '10%', '10%', '10%', '10% (trop...",0.33,-0.827396,False,0.200000,incorrect_low,"[""10% (or 10 percent)"", ""energy loss"", ""biomas..."
1399,validation::694,What gas is actually a waste product of photos...,['oxygen'],oxygen,1.0,"['oxygen', 'oxygen', 'oxygen', 'oxygen', 'oxyg...",-0.00,-1.809155,False,1.000000,incorrect_high,"[""nitrogen"", ""methane"", ""carbon dioxide""]"

In [18]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1400 entries, 0 to 1399
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   id                          1400 non-null   str
 1   question                    1400 non-null   str
 2   ground_truth                1400 non-null   str
 3   low_t_generation            1400 non-null   str
 4   accuracy                    1400 non-null   float64
 5   n_generations               1400 non-null   str
 6   cluster_assignment_entropy  1400 non-null   float64
 7   p_true                      1400 non-null   float64
 8   LLM_verdict                 1400 non-null   bool
 9   C_metric                    1400 non-null   float64
 10  category                    1400 non-null   str
 11  candidate_list              1400 non-null   str
dtypes: bool(1), float64(4), str(7)
memory usage: 581.6 KB

In [19]:
df_subset = df.loc[(df['accuracy']==1.0) & (df['LLM_verdict']==False)]
df_subset

,id,question,ground_truth,low_t_generation,accuracy,n_generations,cluster_assignment_entropy,p_true,LLM_verdict,C_metric,category,candidate_list
16,train::8817,The sum of the masses of the atoms in the form...,['molecular mass'],molar mass,1.0,"['molecular weight', 'molar mass', 'molecular ...",0.94,-0.127772,False,0.327273,incorrect_low,"[""molar mass"", ""atomic mass"", ""formula mass""]"
42,train::7694,What do we call the region on the lung root fo...,['pulmonary plexus'],the pulmonary ligament,1.0,"['pulmonary ligament', 'the pulmonary ligament...",1.75,-0.429533,False,0.072727,incorrect_low,"[""the pulmonary ligament"", ""bronchial tree"", ""..."
104,train::11464,What energy is stored in a person or object?,['potential energy'],kinetic energy,1.0,"['kinetic energy', 'kinetic energy', 'potentia...",0.50,-2.698473,False,0.418182,incorrect_low,"[""kinetic energy"", ""thermal energy"", ""electric..."
136,train::1761,What type of tissue makes up much of the insid...,['ground tissue'],vascular tissue,1.0,"['vascular', 'vascular tissue', 'parenchyma', ...",0.80,-0.388528,False,0.254545,incorrect_low,"[""vascular tissue"", ""epidermal tissue"", ""meris..."
151,validation::1249,When the earth is between the moon and the sun...,['a full moon'],new moon,1.0,"['crescent moon', 'new', 'new moon', 'new moon...",0.80,-0.225791,False,0.236364,incorrect_low,"[""new moon"", ""harvest moon"", ""gibbous moon""]"
152,train::4689,What is the primary cause of air movement in t...,['differences in heating'],differences in air pressure,1.0,"['temperature', 'convection', 'uneven heating ...",1.56,-2.814509,False,0.018182,incorrect_low,"[""differences in air pressure"", ""rotation of t..."
172,train::5779,What does increasing a solute's temperature do?,['increases its solubility'],increases its rate of diffusion,1.0,"['increases the rate of dissolving', 'increase...",1.97,-0.760420,False,0.000000,incorrect_low,"[""increases its rate of diffusion"", ""decreases..."
185,validation::1837,What 3 things do animals need to live and surv...,"['air, water, and food']",food water shelter,1.0,"['air water food', 'food water shelter', 'food...",0.94,-1.811671,False,0.127273,incorrect_low,"[""food water shelter"", ""space, fire, and oxyge..."
200,train::6018,Which system is divided into the somatic and a...,['peripheral nervous system'],nervous system,1.0,"['nervous', 'nervous system', 'the nervous sys...",-0.00,-0.089385,False,0.345455,incorrect_low,"[""nervous system"", ""central nervous system"", ""..."
222,train::7729,Moving electrons have a form of kinetic energy...,['electrical energy'],thermal energy,1.0,"['electrical energy', 'heat', 'electrical ener...",0.67,-2.352830,False,0.272727,incorrect_low,"[""thermal energy"", ""mechanical energy"", ""nucle..."
226,train::256,What is the name of the zone where water is de...,['aphotic zone'],abyssal zone,1.0,"['abyssal zone', 'abyssal zone', 'abyssal zone...",0.33,-0.313956,False,0.654545,incorrect_high,"[""abyssal zone"", ""bathyal zone"", ""hadal zone""]"
247,train::7613,What term describes the energy of an object th...,['mechanical energy'],kinetic energy,1.0,"['kinetic energy', 'kinetic energy', 'kinetic ...",-0.00,-0.161087,False,0.818182,incorrect_high,"[""kinetic energy"", ""thermal energy"", ""electric..."
269,train::6004,"Referring to low what, hypovolemia may be caus...",['blood volume'],blood pressure,1.0,"['blood pressure', 'blood pressure', 'blood pr...",-0.00,-0.113399,False,1.000000,incorrect_high,"[""blood pressure"", ""blood sugar"", ""blood flow""]"
276,train::7030,Portal veins carry blood between what?,['pairs of capillary beds'],capillary beds and the heart,1.0,"['two capillary beds', 'capillary beds and the...",0.64,-0.477345,False,0.218182,incorrect_low,"[""capillary beds and the heart"", ""arteries and..."
299,validation::848,What do you call winds that occur in belts tha...,['global winds'],trade winds,1.0,"['trade winds', 'trade winds', 'trade winds', ...",0.61,-1.911567,False,0.563636,incorrect_high,"[""trade winds"", ""monsoon winds"", ""jet stream""]"
364,train::10605,What are the winds that occur in belts that en...,['global winds'],trade winds,1.0,"['trade winds and westerlies', 'trade winds', ...",0.64,-2.023050,False,0.654545,incorrect_high,"[""trade winds"", ""monsoon winds"", ""jet stream""]"
380,train::1311,What disease is caused when the oomycete plasm...,['downy mildew'],powdery mildew,1.0,"['powdery mildew', 'powdery mildew', 'downey m...",0.90,-2.931546,False,0.236364,incorrect_low,"[""powdery mildew"", ""black rot"", ""botrytis""]"
427,train::3216,What is the type of succession that happens af...,['secondary succession'],primary succession,1.0,"['primary succession', 'secondary succession',...",0.69,-1.911695,False,0.454545,incorrect_low,"[""primary succession"", ""artificial succession""..."
436,train::3796,The point in the titration at which an indicat...,['end point'],equivalence point,1.0,"['equivalence point', 'equivalence point', 'eq...",0.50,-0.826437,False,0.672727,incorrect_high,"[""equivalence point"", ""halfway point"", ""starti..."
446,train::4620,The brain and spinal cord are part of what sys...,['central nervous system'],nervous system,1.0,"['nervous system', 'nervous system', 'nervous'...",-0.00,-0.043590,False,0.672727,incorrect_high,"[""nervous system"", ""circulatory system"", ""sens..."
532,validation::1467,"Club mosses, horsetails, ferns, and whisk fern...",['seedless vascular plants'],vascular plants,1.0,"['vascular plants', 'vascular plants', 'vascul...",0.33,-0.899222,False,0.818182,incorrect_high,"[""vascular plants"", ""non-vascular plants"", ""fl..."
538,train::4724,"Along with nerve tissue, what kind of tissue a...",['brain tissue'],muscle tissue,1.0,"['epithelial tissue', 'muscle tissue', 'epithe...",0.90,-1.914580,False,0.200000,incorrect_low,"[""muscle tissue"", ""connective tissue"", ""epithe..."
560,train::11599,Which zone is located below 200 meters from th...,['aphotic zone'],mesopelagic zone,1.0,"['the mesopelagic zone', 'mesopelagic zone', '...",0.67,-0.899485,False,0.072727,incorrect_low,"[""mesopelagic zone"", ""bathypelagic zone"", ""had..."
562,train::6743,What compound gives tarnished copper it's gree...,['copper carbonate'],copper oxide,1.0,"['copper oxide', 'copper oxide', 'copper oxide...",0.64,-0.898930,False,0.654545,incorrect_high,"[""copper oxide"", ""copper sulfate"", ""copper nit..."
591,train::8556,What colors in a neon sign represent real neon?,"['red, orange']",red orange yellow green and purple,1.0,"['pink orange and red', 'red orange yellow gre...",2.16,-1.706571,False,0.000000,incorrect_low,"[""red orange yellow green and purple"", ""blue a..."
671,train::7608,Oceans are made of a solution of what?,['salt and water'],water,1.0,"['salt water', 'water', 'salt water', 'water',...",0.69,-1.912608,False,0.327273,incorrect_low,"[""water"", ""oxygen"", ""minerals""]"
723,train::3151,What type of cell has negative anode is positi...,['voltaic cell'],electrolytic cell,1.0,"['electrolytic cell', 'galvanic cell', 'electr...",0.69,-0.576252,False,0.218182,incorrect_low,"[""electrolytic cell"", ""galvanic cell"", ""fuel c..."
738,train::3620,What system serves as the relay between the cn...,['autonomic nervous system'],nervous system,1.0,"['nervous system', 'nervous system', 'nervous ...",0.64,-0.429200,False,0.654545,incorrect_high,"[""nervous system"", ""endocrine system"", ""circul..."
739,train::5250,Approximately how many billion years ago did o...,['five billion'],4.6 billion,1.0,"['4.6', 'four and a half billion years ago', '...",0.50,-0.180575,False,0.145455,incorrect_low,"[""4.6 billion"", ""ten billion"", ""two billion""]"
748,train::2903,What occurs when an unstable nucleus emits an ...,['alpha decay'],beta decay,1.0,"['beta decay', 'beta decay', 'beta decay', 'be...",0.33,-4.514488,False,0.818182,incorrect_high,"[""beta decay"", ""gamma radiation"", ""proton emis..."
762,train::1737,What type of energy is used when a roller coas...,['kinetic energy'],potential energy,1.0,"['potential', 'potential energy', 'potential e...",0.64,-0.201829,False,0.509091,incorrect_high,"[""potential energy"", ""thermal energy"", ""electr..."
801,validation::588,"When gasoline is burned, what pollutant is pro...",['carbon dioxide'],carbon monoxide,1.0,"['carbon monoxide', 'carbon monoxide', 'ozone'...",0.80,-0.349485,False,0.527273,incorrect_high,"[""carbon monoxide"", ""nitrogen oxide"", ""sulfur ..."
847,train::255,What is the name of the two metalloids in the ...,['silicon and germanium'],boron and silicon,1.0,"['silicon and germanium', 'Silicon & Germanium...",0.67,-1.914288,False,0.254545,incorrect_low,"[""boron and silicon"", ""arsenic and antimony"", ..."
849,train::4176,What is calculated by adding together the atom...,['molecular mass'],molar mass,1.0,"['molecular mass', 'the molar mass', 'molar ma...",0.69,-0.974692,False,0.181818,incorrect_low,"[""molar mass"", ""atomic mass"", ""formula mass""]"
909,train::11044,The brain and spinal cord are part of what sys...,['central nervous system'],nervous system,1.0,"['nervous system', 'nervous system', 'the nerv...",-0.00,-0.055648,False,0.672727,incorrect_high,"[""nervous system"", ""circulatory system"", ""sens..."
918,train::5498,What traits are those that are inherited uncha...,['dominant traits'],recessive traits,1.0,"['dominant', 'recessive', 'dominant traits', '...",0.69,-1.911158,False,0.200000,incorrect_low,"[""recessive traits"", ""acquired traits"", ""envir..."
952,train::6401,Chemical formulas for ionic compounds are call...,['ionic formulas'],empirical formulas,1.0,"['empirical formulas', 'chemical formulas', 'e...",0.33,-0.898896,False,0.818182,incorrect_high,"[""empirical formulas"", ""structural formulas"", ..."
954,validation::1527,What form the skeletons of most organic molecu...,['carbon chains'],carbon atoms,1.0,"['hydrocarbons', 'carbon atoms', 'carbon atoms...",0.50,-0.226083,False,0.672727,incorrect_high,"[""carbon atoms"", ""hydrogen bonds"", ""oxygen rin..."
959,train::5191,Making a specific prediction based on a genera...,['deductive reasoning'],inductive reasoning,1.0,"['inductive reasoning', 'deductive', 'deductiv...",0.80,-0.281451,False,0.236364,incorrect_low,"[""inductive reasoning"", ""abductive reasoning"",..."
964,train::7488,What three forms does frozen precipitation take?,"['snow, sleet, freezing rain']",snow sleet and hail,1.0,"['snow sleet and hail', 'snow sleet and hail',...",0.94,-0.070907,False,0.272727,incorrect_low,"[""snow sleet and hail"", ""hail and graupel"", ""i..."
975,train::2160,Fruit fly and brine shrimp hox genes have evol...,['400 million years'],50 million years,1.0,"['over 40 million years', '150 million years',...",1.50,-1.138628,False,0.109091,incorrect_low,"[""50 million years"", ""200 million years"", ""600..."
993,train::9724,What term is used to describe a simple diagram...,['food chain'],food web,1.0,"['food web', 'food web', 'food web', 'food web...",0.50,-1.224058,False,0.672727,incorrect_high,"[""food web"", ""energy cycle"", ""trophic level""]"
1044,train::10325,What body system allows humans to move?,['muscular system'],skeletal system,1.0,"['muscular', 'skeletal', 'the skeletal system ...",1.19,-2.245618,False,0.090909,incorrect_low,"[""skeletal system"", ""nervous system"", ""circula..."
1064,train::9558,Adding the number of protons plus the number o...,['atomic number'],atomic mass,1.0,"['atomic mass', 'atomic mass', 'atomic mass', ...",0.33,-0.974735,False,0.654545,incorrect_high,"[""atomic mass"", ""molecular weight"", ""isotopic ..."
1093,train::4779,Carbon and what are the second and third most ...,['hydrogen'],oxygen and hydrogen,1.0,"['oxygen and hydrogen', 'oxygen and hydrogen',...",1.09,-0.180459,False,0.400000,incorrect_low,"[""oxygen and hydrogen"", ""nitrogen"", ""calcium""]"
1180,train::4990,"These types of cella support young, growing pa...",['collenchyma cells'],parenchyma cells,1.0,"['parenchyma cells', 'parenchyma cells', 'pare...",-0.00,-0.758442,False,0.490909,incorrect_low,"[""parenchyma cells"", ""sclerenchyma cells"", ""xy..."
1192,train::9608,All atoms have equal numbers of what two parti...,['electrons and protons'],protons and neutrons,1.0,"['protons and neutrons', 'protons and neutrons...",0.33,-1.314192,False,0.654545,incorrect_high,"[""protons and neutrons"", ""neutrons and electro..."
1392,train::5730,What type of acid is often used as a preservat...,['benzoic acid'],citric acid,1.0,"['citric acid', 'citric acid', 'citric acid', ...",-0.00,-0.070538,False,0.672727,incorrect_high,"[""citric acid"", ""acetic acid"", ""tartaric acid""]"
1397,train::8773,Carbon dioxide is an example of a material tha...,['sublimation'],sublimation,1.0,"['sublimation', 'sublimation', 'sublimation', ...",0.33,-0.693766,False,0.818182,incorrect_high,"[""distillation"", ""ionization"", ""crystallization""]"
1399,validation::694,What gas is actually a waste product of photos...,['oxygen'],oxygen,1.0,"['oxygen', 'oxygen', 'oxygen', 'oxygen', 'oxyg...",-0.00,-1.809155,False,1.000000,incorrect_high,"[""nitrogen"", ""methane"", ""carbon dioxide""]"

In [20]:
df_subset.shape

(50, 12)

In [21]:
df_subset.to_csv("/home/kalashkala/output/sampled_1400_uncertainty_run_llama_sciq_combined_llm_verdict_concentration_output_with_distractors_accuracy1_llmverdictfalse.csv")

In [ ]:
df_math = pd.read_csv("/home/kalashkala/recovery-gaps-experiment/data/sampled_all_uncertainty_run_mistral_answerable_math_combined_llm_verdict_concentration_output_with_distractors.csv")
# df_math = df_math.drop(columns=['Unnamed: 0'])
# df_math.to_csv("/home/kalashkala/recovery-gaps-experiment/data/sampled_all_uncertainty_run_qwen_answerable_math_combined_llm_verdict_concentration_output_with_distractors.csv",index=False)
df_math.loc[df_math['low_t_generation'].isna() == True]

,id,ground_truth,low_t_generation,accuracy,n_generations,cluster_assignment_entropy,question,p_true,LLM_verdict,C_metric,category,candidate_list
1016,validation::146,['4'],NaN,0.0,"['None', 'none', 'Remainder 3', '8 (remainder)...",1.5,"There were 44 laptops in the shop, and Mike di...",-0.890503,False,0.054545,incorrect_low,"[""nan"", ""2"", ""1""]"

: